- name: Clean up server side
  hosts: server
  gather_facts: false
  tasks:
    - name: Register end time
      shell: date -u +%Y-%m-%dT%H:%M:%S
      register: date
    - set_fact:
        end_time: "{{ date.stdout }}"
    - name: Extract and save metrics from prometheus
      import_tasks: extract_metrics.yml

- name: Set end time on localhost
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Register monotime end_time
    shell: python -u -c 'import time; print(time.monotonic())'
    register: time_mono
  - set_fact:
      mono_time_end: "{{time_mono.stdout}}"
  - name: 5s grace period
    pause:
      seconds: 5

- name: kill java and prometheus
  hosts: server
  gather_facts: false
  tasks:
    - name: Kill java
      command: "killall java"
      ignore_errors: true
    - name: Kill prometheus
      command: "killall prometheus"   
      ignore_errors: true
    - name: 5s grace period
      pause:
        seconds: 5

- name: Clean up from experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug print localhost side
      debug:
        var: hostvars[inventory_hostname]
    - name: Process Jolokia ticktime
      shell: cd python_scripts && python plot_tick_times.py "{{playbook_dir}}"/results "{{timestamp}}" "{{playbook_dir}}"/results/"{{timestamp}}"/tick_times.json "{{mono_time_start}}" "{{mono_time_end}}"
    - name: Process metrics
      shell: "cd python_scripts && python process_metrics.py {{playbook_dir}}/results/{{timestamp}}/metrics.json {{playbook_dir}}/configuration_files/metric_names.json {{playbook_dir}}/results {{timestamp}}"
    - name: Cancel reservation
      shell: |
        module load prun
        preserve -c {{ reservation_number}}w
