- name: Clean up server side
  hosts: server
  gather_facts: false
  tasks:
    - name: Register end time
      shell: date -u +%Y-%m-%dT%H:%M:%S
      register: date
    - set_fact:
        end_time: "{{ date.stdout }}"
    - name: Extract and save metrics from prometheus
      import_tasks: extract_metrics.yml
    - name: Kill java
      command: "killall java"
      ignore_errors: true
    - name: Kill prometheus
      command: "killall prometheus"   
      ignore_errors: true

- name: Clean up from experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Process Jolokia ticktime
      shell: "cd python_scripts && python plot_tick_times.py {{playbook_dir}}/results {{timestamp}} {{playbook_dir}}/results/{{timestamp}}/tick_times.json"
    - name: Process metrics
      shell: "cd python_scripts && python process_metrics.py {{playbook_dir}}/results/{{timestamp}}/metrics.json {{playbook_dir}}/configuration_files/metric_names.json {{playbook_dir}}/results {{timestamp}}"
    - name: Cancel reservation
      shell: |
        module load prun
        preserve -c {{ reservation_number}}w
