---
- hosts: localhost
  pre_tasks:
    - name: Download minecraft
      get_url:
        url: https://piston-data.mojang.com/v1/objects/15c777e2cfe0556eef19aab534b186c0c6f277e1/server.jar
        dest: "{{playbook_dir}}/server.jar"
    - name: Download JMX exporter
      get_url:
        url: https://repo.maven.apache.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar
        dest: "{{playbook_dir}}/jmx_prometheus_javaagent-0.20.0.jar"
    - name: "Download Node exporter Tar Ball"
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
        dest: "{{playbook_dir}}/node-exporter.tar.gz"
    - name: "Unpack node exporter tar ball"
      unarchive:
        src: "{{playbook_dir}}/node-exporter.tar.gz"
        dest: "{{playbook_dir}}"
    - name: remove old exporter dir if it exists
      shell: rm -rf node_exporter_dir
    - name: rename dir
      shell: mv node_exporter-1.8.1.linux-amd64 node_exporter_dir
    - name: "Remove archive"
      file: 
        path: "{{playbook_dir}}/node-exporter.tar.gz"
        state: absent
    - name: "Download Prometheus"
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz
        dest: "{{playbook_dir}}/prometheus-archive.tar.gz"
    - name: "Unpack Prometheus"
      unarchive:
        src: "{{playbook_dir}}/prometheus-archive.tar.gz"
        dest: "{{playbook_dir}}"
    - name: "Remove archive"
      file: 
        path: "{{playbook_dir}}/prometheus-archive.tar.gz"
        state: absent
    - name: "Rename directory"
      shell: |
        mv -n prometheus-2.51.2.linux-amd64 prometheus
    - name: "Place prometheus_config.yml"
      copy:
        src: "{{playbook_dir}}/configuration_files/prometheus_config.yml"
        dest: "{{playbook_dir}}/prometheus/prometheus_config.yml"
    - name: Install python libraries
      shell: pip install matplotlib numpy --ignore-installed --quiet
    - name: Set result folder timestamp
      shell: date -u +%Y-%m-%dT%H:%M:%S
      register: date
    - set_fact:
        timestamp: "{{ date.stdout }}"
      
    

