- name: clean up server side
  hosts: server
  gather_facts: false
  tasks:
    - name: Set end time
      shell: date -u +%Y-%m-%dT%H:%M:%S
      register: date
    - set_fact:
        end_time: "{{ date.stdout }}"
    - name: Retrieve tick times
      uri:
        url: "http://localhost:9090/api/v1/query_range?query=net_minecraft_server_Server_averageTickTime&start={{start_time}}.999Z&end={{end_time}}.000Z&step=5s"
      register: query
      ignore_errors: true
    - name: Server side debug print
      debug:
        var: hostvars[inventory_hostname]
    - name: pause to allow inspection
      pause:
        seconds: 100
    - name: Kill java
      command: "killall java"
      ignore_errors: true
    - name: Kill prometheus
      command: "killall prometheus"   

- name: Clean up from experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Cancel reservation
      shell: |
        module load prun
        preserve -c {{ reservation_number}}