- name: clean up server side
  hosts: server
  gather_facts: false
  tasks:
    - name: Set end time
      shell: date -u +"%Y-%m-%dT%H:%M:%S.%N" | awk '{printf("%sZ\n", substr($0, 1, 23))}'
      register: date
    - set_fact:
        end_time: "{{ date.stdout }}"
    - name: Retrieve tick times
      uri:
        url: http://localhost:9090/api/v1/query_range?query=up&start="{{start_time}}"&end="{{end_time}}"&step=15s
      register: query
    - name: Server side debug print
      debug:
        var: hostvars[inventory_hostname]
    - name: Kill java
      command: "killall java"
      ignore_errors: true
    - name: Kill prometheus
      command: "killall prometheus"   
   
   
#cleanup from the experiment, for now its just cancelling the reservation
- name: Clean up from experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Cancel reservation
      shell: |
        module load prun
        preserve -c {{ reservation_number}}