# LAUNCH PROGRAMS
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Run server
      shell: |
        module load java/jdk-1.8.0
        cd server
        java -Xmx10240M -Xms100240M -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Sleep 1
      pause:
        seconds: 1
    - name: Get server PID
      shell: |
        pgrep -u "$(whoami)" -f "^java -jar .*/server.jar"
      register: output
    - name: Print server PID
      shell: |
        echo "{{output}}"

# STOP PROGRAMS
- hosts: server
  gather_facts: False
  tasks:
    - name: Kill java
      shell: "killall java"
      ignore_errors: True
