# LAUNCH PROGRAMS
- name: Run experiment
  hosts: server
  gather_facts: false
  tasks:
    - name: Run server and jmx exporter agent
      shell: >  
        module load java/jdk-19 && cd server &&
        java -Dcom.sun.management.jmxremote.port=9999
        -javaagent:./jmx_prometheus_javaagent-0.20.0.jar=12345:jmxexp_config.yml
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false 
        -Xmx10240M
        -Xms10240M
        -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Start prometheus
      shell: |
        cd ./prometheus
        ./prometheus --config.file=prometheus_config.yml
      async: "{{experiment_duration_s}}"
      poll: 0
    - name: Allow server 60 seconds to start up
      pause:
        seconds: 60
    - name: Sleep during experiment
      pause:
        seconds:"{{experiment_duration_s}}"


- name: Run client play
  hosts:  client
  tasks:
  # Wait for server to be started before running script
    - name: Run bot script
      shell: |
        node bots.js
      async: "{{experiment_duration_s}}"
      poll: 0
    - name: Sleep during experiment
      pause:
        seconds:"{{experiment_duration_s}}"








- name: Stop programs
  hosts: all
  gather_facts: false
  tasks:
    - name: Kill java
      command: "killall java"
      ignore_errors: true
    - name: Kill prometheus
      command: "killall prometheus"
    - name: Cancel reservation
      shell: |
        module load prun
        preserve -c {{ reservation_number }}
