# LAUNCH PROGRAMS
- name: Run experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run server
      shell: >
        module load java/jdk-19 && cd server &&
        java -Dcom.sun.management.jmxremote.port=9999
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false 
        -Xmx10240M
        -Xms10240M
        -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Start JMX exporter http server
      shell: |
        cd server
        java -jar jmx_prometheus_httpserver-0.20.0.jar 12345 prom_config.yml
      async: "{{experiment_duration_s}}"
    - name: Sleep during experiment
      pause:
        seconds: 180



- name: Stop programs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Kill java
      command: "killall java"
      ignore_errors: true
