# LAUNCH PROGRAMS
- hosts: server
  gather_facts: False
  tasks:
    - name: Run server
      shell: |
        module load java/jdk-1.8.0
        cd server
        java -Xmx1024M -Xms1024M -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Sleep 1
      pause:
        seconds: 1

- hosts: client
  gather_facts: False
  tasks:
    - name: Wait for server to be ready
      pause:
        seconds: 30
    - set_fact:
        server_ib_ip: "{{ '10.149.0.' ~ (groups['server'][0][-2:] | int) }}"

# STOP PROGRAMS
- hosts: server
  gather_facts: False
  tasks:
    - name: Kill java
      shell: "killall java"
      ignore_errors: True
