# LAUNCH PROGRAMS
- name: Run experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run server and jmx exporter agent
      shell: >
        module load java/jdk-19 && cd server &&
        java -Dcom.sun.management.jmxremote.port=9999
        -javaagent:./jmx_prometheus_javaagent-0.20.0.jar=12345:jmxexp_config.yml
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false 
        -Xmx10240M
        -Xms10240M
        -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Start prometheus
      shell: |
        cd /server/prometheus/
        ./prometheus --config.file=prometheus_config.yml --web.listen-address=127.0.0.1:9090 --log.level=debug
      async: "{{experiment_duration_s}}"
      poll: 0
    - name: Sleep during experiment
      pause:
        seconds: 180



- name: Stop programs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Kill java
      command: "killall java"
      ignore_errors: true
