# LAUNCH PROGRAMS
- name: Run experiment
  hosts: server
  gather_facts: false
  tasks:
    - name: Run server and jmx exporter agent
      shell: >  
        module load java/jdk-19 && cd "{{minecraft_tmp_dir.path}}" &&
        java -Dcom.sun.management.jmxremote.port=9999
        -javaagent:./jmx_prometheus_javaagent-0.20.0.jar=12345:jmxexp_config.yml
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false 
        -Xmx10240M
        -Xms10240M
        -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Start prometheus
      shell: |
        cd "{{prometheus_tmp_dir.path}}/prometheus"
        ./prometheus --config.file=prometheus_config.yml
      async: "{{experiment_duration_s}}"
      poll: 0
    - name: Set start time fact
      shell: date -u +%Y-%m-%dT%H:%M:%S
      register: date
    - set_fact:
        start_time: "{{ date.stdout }}"
    - name: Server side debug print
      debug:
        var: hostvars[inventory_hostname]
    - name: Allow server 60 seconds to start up
      pause:
        seconds: 60

- name: Run client play
  hosts: localhost
  gather_facts: false
  tasks:
    - set_fact:
         server_ib_ip: "{{ '10.149.0.' ~ (groups['server'][0][-2:] | int) }}" 
    - name: Run bot script
      shell: |
        cd "{{playbook_dir}}" && node bots.js {{server_ib_ip}}
      async: "{{experiment_duration_s}}"
      poll: 0
    - name: Sleep during experiment
      pause:
        seconds:"{{experiment_duration_s}}"
