# LAUNCH PROGRAMS
- name: Run experiment
  hosts: server
  gather_facts: false
  tasks:
    - name: Run MVE server and JMX exporter agent
      shell: cd "{{minecraft_tmp_dir.path}}" && {{JVM_config_parameters}}
      async: "{{server_runtime_s}}"
      register: java_debug
      poll: 0
    - name: Java_debug print
      debug:
        var: java_debug
    - name: Java print version
      shell: java -version
      register: java_version
    - name: Print java_version
      debug:
        var: java_version
    - name: Start Node exporter
      shell: "cd {{playbook_dir}} && cd node_exporter_dir && ./node_exporter"
      async: "{{server_runtime_s}}"
      poll: 0
    - name: Start Prometheus
      shell: |
        cd "{{prometheus_tmp_dir.path}}/prometheus"
        ./prometheus --config.file=prometheus_config.yml
      async: "{{server_runtime_s}}"
      poll: 0
    - name: Register start time
      shell: date -u +%Y-%m-%dT%H:%M:%S
      register: date
    - set_fact:
        start_time: "{{date.stdout}}"
    - name: Server hostvars debug
      debug:
        var: hostvars[inventory_hostname]
    - name: Server start up
      pause:
        seconds: 60

- name: Run client play
  hosts: clients
  gather_facts: false
  tasks:
    - set_fact:
         server_ib_ip: "{{ '10.149.0.' ~ (groups['server'][0][-2:] | int) }}"      
    - name: Run player simulation
      shell: eval "$(conda shell.bash hook)" && conda activate scratch && cd "{{playbook_dir}}/bot_scripts" && node {{bot_behavior_script}} {{server_ib_ip}} {{ansible_host}} {{players_per_node}}
      async: "{{experiment_duration_s}}"
      register: player_sim_result
      poll: 0
    - name: print result
      debug:
        var: player_sim_result
    - name: Print server IP
      debug:
        var: server_ib_ip 

- name: Run Jolokia python script on server node
  hosts: server
  gather_facts: false
  tasks:
    - name: Start tick time python script
      shell: python "{{playbook_dir}}/python_scripts/jolokia_get_minecraft_tick.py"
      async: "{{server_runtime_s}}"
      poll: 0
      register: jolokia_response
    - name: output jolokia response
      debug:
        var: jolokia_response
    - name: Sleep during experiment
      pause:
        seconds: "{{experiment_duration_s}}"
