# LAUNCH PROGRAMS
- name: Run experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run server
      shell: |
        module load java/jdk-19 && cd server
        java java -Dcom.sun.management.jmxremote.port=9999 \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Xmx10240M -Xms10240M -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Sleep while server startsup
      pause:
        seconds: 5
    - name: run prometheus
      shell: |
        cd server
        java -javaagent:./jmx_prometheus_javaagent-0.20.0.jar=12345:config.yaml -jar jmx_prometheus.jar



- name: Stop programs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Kill java
      command: "killall java"
      ignore_errors: true
