# LAUNCH PROGRAMS
- name: Run experiment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run server
      shell: module load java/jdk-19 && cd server && java -Xmx10240M -Xms10240M -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 0
    - name: Validate JMXterm presence
      shell: |
          cd server
          ls -a
          pwd
    - name: Start JMXterm
      shell: cd server && java -jar jmxterm-1.0.4-uber.jar --noninteract --output output.txt
    - name: try to submit command to jmxterm
      shell: echo get -s -b java.lang:type=Runtime Name | \
        java -jar target/jmxterm-1.0.4-uber.jar \
        -l localhost:9991 -v silent -n
    - name: Sleep during experiment
      pause:
        seconds: 70



- name: Stop programs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Kill java
      command: "killall java"
      ignore_errors: true
