# LAUNCH PROGRAMS
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Run server
      shell: |
        module load java/jdk-19
        cd server
        java -Xmx10240M -Xms10240M -jar server.jar nogui
      async: "{{ experiment_duration_s }}"
      poll: 1
    - name: Sleep 1
      pause:
        seconds: 1

# STOP PROGRAMS
- hosts: server
  gather_facts: False
  tasks:
    - name: Kill java
      shell: "killall java"
      ignore_errors: True
