- name: Install openJDK 19
  hosts: servers
  tasks:
    - name: Set the package manager fact
      ansible.builtin.set_fact: _pkg_mgr="apt"
    - name: ensure openJDK 19 JDK install
      ansible.builtin.apt:
        name: openjdk-19-jdk
        state: present
    - name: ensure openJDK 19 JRE install
      ansible.builtin.apt:
        name: openjdk-19-jre
        state: present
    - name: run the server
      ansible.builtin.shell:
        cmd: cd server && java -Xmx1024M -Xms1024M -jar server.jar nogui
        # cmd: cd server && java -Xmx1024M -Xms1024M -jar server.jar

        #connect to server by ::1 while running on wsl on my windows machine
